#ifndef DEFINES_H
#define DEFINES_H

#define RENDER_WOBBLE 0.1

#define CHUNKLEVELS 4
#define WORLDSIZE 25

#define WORLDGEN_BUMPYNESS 3
#define WORLDGEN_RANGE 0.5

#define DIAMONDSQUARELEVELS 10

#define SPEED 55
#define PLAYER_FRICTION 20.0
#define FORCE 150
#define GRAVITY 20
#define JUMPSPEED 7
#define MOUSE_SENSITIVITY (1.1/800.0)

#define PLAYER_HEIGHT 3.7
#define PLAYER_EYEHEIGHT 3.4
#define PLAYER_MASS 30
#define PLAYER_WIDTH 1.8

#endif //DEFINES_H
